name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install tabix
      - name: Install tabix
        run: |
          sudo apt-get update
          sudo apt-get install -y htslib-bin
          echo "Installed packages:"
          dpkg -l | grep hts
          echo "Contents of htslib-bin:"
          dpkg -L htslib-bin

      - name: Verify tools
        run: |
          set -e  # Make script exit on first error
          which bgzip || { echo "bgzip not found"; exit 1; }
          which tabix || { echo "tabix not found"; exit 1; }
          bgzip --version
          tabix --version

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        run: cargo test

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo clippy -- -D warnings
