name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

        # presently does not work
        #- name: Install tabix
        #  run: |
        #    sudo apt-get update
        #    sudo apt-get install -y tabix
        #    which bgzip
        #    bgzip --version
        #    which tabix
        #    tabix --version

        #- name: Create test directories
        #  run: |
        #    mkdir -p target/test_files
        #    chmod 777 target/test_files

        #- name: Cache dependencies
        #  uses: actions/cache@v3
        #  with:
        #    path: |
        #      ~/.cargo/registry
        #      ~/.cargo/git
        #      target
        #    key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        run: RUST_BACKTRACE=1 cargo test --verbose --lib # integration test uses bgzip, which has install isues

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo clippy -- -D warnings
